# Generated by Django 6.1 on 2026-08-30 15:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumberCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.PositiveIntegerField(default=0, verbose_name='último número usado')),
            ],
            options={
                'verbose_name': 'contador de OS',
                'verbose_name_plural': 'contador de OS',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identificador público')),
                ('number', models.PositiveIntegerField(db_index=True, editable=False, unique=True, verbose_name='número da OS')),
                ('entry_km', models.PositiveIntegerField(verbose_name='KM de entrada')),
                ('entry_at', models.DateTimeField(db_index=True, verbose_name='data/hora de entrada')),
                ('customer_complaint', models.TextField(verbose_name='reclamação do cliente')),
                ('diagnosis', models.TextField(blank=True, verbose_name='diagnóstico')),
                ('diagnosis_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='diagnóstico atualizado em')),
                ('internal_notes', models.TextField(blank=True, verbose_name='observações internas')),
                ('expected_delivery_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='previsão de entrega')),
                ('status', models.CharField(choices=[('AGUARDANDO_AVALIACAO', 'Aguardando avaliação'), ('EM_AVALIACAO', 'Em avaliação'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('AGUARDANDO_PECA', 'Aguardando peça'), ('EM_MANUTENCAO', 'Em manutenção'), ('FINALIZADO', 'Finalizado'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], db_index=True, default='AGUARDANDO_AVALIACAO', max_length=25, verbose_name='status')),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10, verbose_name='prioridade')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finalizado em')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='entregue em')),
                ('exit_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM de saída')),
                ('exit_notes', models.TextField(blank=True, verbose_name='observação de saída')),
                ('exit_km_justification', models.TextField(blank=True, verbose_name='justificativa do KM de saída')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelado em')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL, verbose_name='cancelado por')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='customers.client', verbose_name='cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_orders', to=settings.AUTH_USER_MODEL, verbose_name='entregue por')),
                ('diagnosis_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosed_orders', to=settings.AUTH_USER_MODEL, verbose_name='diagnóstico atualizado por')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to='vehicles.vehiclelocation', verbose_name='localização')),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='mecânico responsável')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='vehicles.vehicle', verbose_name='veículo')),
            ],
            options={
                'verbose_name': 'ordem de serviço',
                'verbose_name_plural': 'ordens de serviço',
                'ordering': ['-entry_at', '-number'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('previous_status', models.CharField(blank=True, choices=[('AGUARDANDO_AVALIACAO', 'Aguardando avaliação'), ('EM_AVALIACAO', 'Em avaliação'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('AGUARDANDO_PECA', 'Aguardando peça'), ('EM_MANUTENCAO', 'Em manutenção'), ('FINALIZADO', 'Finalizado'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], max_length=25, verbose_name='status anterior')),
                ('new_status', models.CharField(choices=[('AGUARDANDO_AVALIACAO', 'Aguardando avaliação'), ('EM_AVALIACAO', 'Em avaliação'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('AGUARDANDO_PECA', 'Aguardando peça'), ('EM_MANUTENCAO', 'Em manutenção'), ('FINALIZADO', 'Finalizado'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], max_length=25, verbose_name='status novo')),
                ('changed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='data/hora')),
                ('note', models.TextField(blank=True, verbose_name='observação')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='workorders.serviceorder', verbose_name='ordem de serviço')),
            ],
            options={
                'verbose_name': 'histórico de status',
                'verbose_name_plural': 'histórico de status',
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['status'], name='workorders__status_23d9af_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['entry_at'], name='workorders__entry_a_2f2244_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['expected_delivery_at'], name='workorders__expecte_90733b_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['number'], name='workorders__number_d14c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorderstatushistory',
            index=models.Index(fields=['service_order', '-changed_at'], name='workorders__service_39659a_idx'),
        ),
    ]
