# Generated by Django 6.1 on 2026-08-30 17:49

import apps.workorders.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_plate'),
        ('workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='vistoriado em')),
                ('fuel_level', models.CharField(choices=[('NAO_VERIFICADO', 'Não verificado'), ('RESERVA', 'Reserva'), ('1_4', '1/4'), ('1_2', '1/2'), ('3_4', '3/4'), ('CHEIO', 'Cheio')], default='NAO_VERIFICADO', max_length=14, verbose_name='nível de combustível')),
                ('notes', models.TextField(blank=True, verbose_name='observações gerais')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL, verbose_name='vistoriado por')),
                ('service_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='workorders.serviceorder', verbose_name='ordem de serviço')),
            ],
            options={
                'verbose_name': 'vistoria',
                'verbose_name_plural': 'vistorias',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('OS_CRIADA', 'OS criada'), ('STATUS_ALTERADO', 'Status alterado'), ('MECANICO_ALTERADO', 'Mecânico alterado'), ('PREVISAO_ALTERADA', 'Previsão alterada'), ('LOCALIZACAO_ALTERADA', 'Localização alterada'), ('DIAGNOSTICO_ATUALIZADO', 'Diagnóstico atualizado'), ('SERVICO_ADICIONADO', 'Serviço adicionado'), ('SERVICO_INICIADO', 'Serviço iniciado'), ('SERVICO_CONCLUIDO', 'Serviço concluído'), ('SERVICO_REABERTO', 'Serviço reaberto'), ('SERVICO_CANCELADO', 'Serviço cancelado'), ('FOTOS_ADICIONADAS', 'Fotos adicionadas'), ('FOTO_REMOVIDA', 'Foto removida'), ('VISTORIA_SALVA', 'Vistoria registrada'), ('OS_FINALIZADA', 'Serviço finalizado'), ('VEICULO_ENTREGUE', 'Veículo entregue'), ('OS_CANCELADA', 'OS cancelada')], db_index=True, max_length=30, verbose_name='evento')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='dados')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='data/hora')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workorders.serviceorder', verbose_name='ordem de serviço')),
            ],
            options={
                'verbose_name': 'registro de atividade',
                'verbose_name_plural': 'registros de atividade',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['service_order', '-created_at'], name='workorders__service_0c9446_idx')],
            },
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40, verbose_name='chave')),
                ('label', models.CharField(max_length=80, verbose_name='item')),
                ('condition', models.CharField(choices=[('NAO_VERIFICADO', 'Não verificado'), ('OK', 'OK'), ('ATENCAO', 'Atenção'), ('AVARIA', 'Avaria')], default='NAO_VERIFICADO', max_length=14, verbose_name='condição')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='observação')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workorders.inspection', verbose_name='vistoria')),
            ],
            options={
                'verbose_name': 'item da vistoria',
                'verbose_name_plural': 'itens da vistoria',
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('inspection', 'key'), name='unique_inspection_item_key')],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identificador público')),
                ('category', models.CharField(choices=[('ENTRADA', 'Entrada'), ('VISTORIA', 'Vistoria'), ('DIAGNOSTICO', 'Diagnóstico'), ('SERVICO', 'Durante o serviço'), ('SAIDA', 'Saída')], db_index=True, default='ENTRADA', max_length=12, verbose_name='categoria')),
                ('image', models.ImageField(upload_to=apps.workorders.models.photo_upload_to, verbose_name='imagem')),
                ('caption', models.CharField(blank=True, max_length=160, verbose_name='legenda')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='removida')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='removida em')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_photos', to=settings.AUTH_USER_MODEL, verbose_name='removida por')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='workorders.serviceorder', verbose_name='ordem de serviço')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to=settings.AUTH_USER_MODEL, verbose_name='enviada por')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='vehicles.vehicle', verbose_name='veículo')),
            ],
            options={
                'verbose_name': 'foto',
                'verbose_name_plural': 'fotos',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['service_order', 'category'], name='workorders__service_0c2d4e_idx'), models.Index(fields=['vehicle', '-created_at'], name='workorders__vehicle_c9ab72_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=120, verbose_name='serviço')),
                ('requested_description', models.TextField(blank=True, verbose_name='descrição solicitada')),
                ('performed_service', models.TextField(blank=True, verbose_name='serviço realizado')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_EXECUCAO', 'Em execução'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDENTE', max_length=12, verbose_name='situação')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_tasks', to=settings.AUTH_USER_MODEL, verbose_name='mecânico')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workorders.serviceorder', verbose_name='ordem de serviço')),
            ],
            options={
                'verbose_name': 'serviço da OS',
                'verbose_name_plural': 'serviços da OS',
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['service_order', 'position'], name='workorders__service_451284_idx')],
            },
        ),
    ]
