# Generated by Django 6.1 on 2026-08-30 20:39

import apps.workorders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_inspection_activitylog_inspectionitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='delivery_signature',
            field=models.ImageField(blank=True, null=True, upload_to=apps.workorders.models.signature_upload_to, verbose_name='assinatura da entrega'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='received_by_document',
            field=models.CharField(blank=True, max_length=30, verbose_name='documento de quem retirou'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='received_by_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='retirado por'),
        ),
    ]
