# Generated by Django 6.1 on 2026-08-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_serviceorder_delivery_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderphoto',
            name='angle',
            field=models.CharField(blank=True, choices=[('FRENTE', 'Frente'), ('TRASEIRA', 'Traseira'), ('LATERAL_ESQ', 'Lateral esquerda'), ('LATERAL_DIR', 'Lateral direita'), ('DIAGONAL', 'Diagonal dianteira'), ('EXTRA', 'Foto extra')], db_index=True, default='EXTRA', help_text='Posição guiada da vistoria (frente, traseira…) ou EXTRA.', max_length=16, verbose_name='ângulo / posição'),
        ),
    ]
