# Generated by Django 6.1 on 2026-08-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0004_photo_angle'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='dado de demonstração'),
        ),
    ]
