# Generated by Django 6.1 on 2026-08-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0005_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='brought_by_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='quem trouxe o veículo'),
        ),
    ]
