# Generated by Django 6.1 on 2026-08-30 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identificador público')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='nome')),
                ('phone', models.CharField(db_index=True, max_length=11, verbose_name='telefone')),
                ('phone_whatsapp', models.CharField(blank=True, max_length=11, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=14, verbose_name='CPF/CNPJ')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='customers_c_name_301e2e_idx'), models.Index(fields=['phone'], name='customers_c_phone_be3650_idx')],
            },
        ),
    ]
