# Generated by Django 6.1 on 2026-08-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
    ]
