# Generated by Django 6.1 on 2026-08-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_client_cpf_cnpj_alter_client_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, help_text='Marcado pelo carregamento de exemplos; removido pelo botão na Configurações.', verbose_name='dado de demonstração'),
        ),
    ]
