# Generated by Django 6.1 on 2026-08-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, help_text='Usuário criado pelo pacote de exemplos.', verbose_name='dado de demonstração'),
        ),
    ]
