# Generated by Django 6.1 on 2026-08-30 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nome')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'localização',
                'verbose_name_plural': 'localizações',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identificador público')),
                ('plate', models.CharField(db_index=True, max_length=7, unique=True, verbose_name='placa')),
                ('brand', models.CharField(max_length=40, verbose_name='marca')),
                ('model', models.CharField(max_length=60, verbose_name='modelo')),
                ('version', models.CharField(blank=True, max_length=60, verbose_name='versão')),
                ('model_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ano do modelo')),
                ('manufacture_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ano de fabricação')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='cor')),
                ('fuel', models.CharField(blank=True, choices=[('FLEX', 'Flex'), ('GASOLINA', 'Gasolina'), ('ETANOL', 'Etanol'), ('DIESEL', 'Diesel'), ('GNV', 'GNV'), ('ELETRICO', 'Elétrico'), ('HIBRIDO', 'Híbrido')], max_length=10, verbose_name='combustível')),
                ('chassis', models.CharField(blank=True, max_length=30, verbose_name='chassi')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='customers.client', verbose_name='cliente atual')),
            ],
            options={
                'verbose_name': 'veículo',
                'verbose_name_plural': 'veículos',
                'ordering': ['plate'],
                'indexes': [models.Index(fields=['plate'], name='vehicles_ve_plate_f1ecfa_idx')],
            },
        ),
    ]
