# Generated by Django 6.1 on 2026-08-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='placa'),
        ),
    ]
