# Generated by Django 6.1 on 2026-08-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='dado de demonstração'),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='dado de demonstração'),
        ),
    ]
